---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 8df73b037f64525804ac1f4dfbd8b13a51e4cc21
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
  labels:
    expose: "true"
    app: i-ptg-test-get-lead
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg-test-get-lead
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-ptg-test-get-lead
    provider: fabric8
    group: com.redhat
